"""Evidence export — signed zip + PDF report + bundled verifier (CLAUDE.md §10).

The single user-visible button on case detail. Investigators use this to
hand evidence off to editors, peers, opposing counsel, or courts. The
recipient does not need Capsule installed — ``verify.py`` is a standalone
script that re-checks every signature and the audit chain with only
``cryptography`` as a dependency.

Bundle layout::

    {case_slug}_{utc_timestamp}.zip
    ├── manifest.json
    ├── manifest.sig
    ├── public_key.pem
    ├── case_report.pdf
    ├── audit_log.json
    ├── verify.py
    ├── README.txt
    └── downloads/
        └── {stem}/                     ← per-item folder (CLAUDE.md §5/§6)
            ├── {media_filename}        ← present for media kind
            ├── {stem}.manifest.pdf
            ├── {stem}.meta.json
            ├── {stem}.meta.json.sig
            ├── {stem}.checksums.txt
            └── {stem}.page.*           ← MHTML, screenshot, WARC, etc.

The manifest is a flat list of ``{path, role, size, md5, sha256}`` records
covering every file in the bundle. We sign the manifest, not each file
individually — the verifier re-derives per-file hashes against the manifest.
"""

from __future__ import annotations

import datetime as _dt
import io
import json
import sqlite3
import zipfile
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import (
    __version__,
    audit,
    cases,
    config,
    pdf_report,
    postprocess,
    signing,
)

__all__ = [
    "EXPORT_README_NAME",
    "ExportPlan",
    "ExportResult",
    "build_bundle",
    "verifier_template_path",
]


EXPORT_README_NAME = "README.txt"


def verifier_template_path() -> Path:
    return config.APP_DIR / "templates" / "verify.py.tmpl"


@dataclass(frozen=True)
class ExportPlan:
    case: cases.Case
    items: list[sqlite3.Row]


@dataclass(frozen=True)
class ExportResult:
    zip_path: Path
    manifest_path: Path
    audit_log_entry_id: int


def _utcnow_compact() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def plan_for_case(conn: sqlite3.Connection, case_id: int) -> ExportPlan:
    """Collect everything needed for a per-case bundle."""
    case = cases.get(conn, case_id)
    if case is None:
        raise LookupError(f"case {case_id} not found")
    rows = list(
        conn.execute(
            "SELECT * FROM downloads WHERE case_id = ? ORDER BY capture_date ASC",
            (case_id,),
        )
    )
    return ExportPlan(case=case, items=rows)


def _iter_artifact_paths(plan: ExportPlan) -> Iterable[tuple[Path, str, str]]:
    """Yield ``(absolute, relative_in_zip, role)`` for every artifact.

    Track A layout: each library item has a single per-item folder
    ``/downloads/{case_slug}/{stem}/`` that holds the media file (if any),
    every sidecar, and the meta + signature + checksums files. The bundle
    mirrors this flat layout under ``downloads/{stem}/...``.
    """
    for row in plan.items:
        meta = json.loads(row["meta_json"])
        item_rel = row["item_dir"]  # relative to /downloads
        item_abs = config.DOWNLOADS_DIR / item_rel
        stem = item_abs.name

        # Media file (if any) lives in the same per-item folder.
        if row["relative_path"]:
            yield (
                config.DOWNLOADS_DIR / row["relative_path"],
                f"downloads/{stem}/{Path(row['relative_path']).name}",
                "media",
            )

        # Every artifact recorded in meta.json. Covers MHTML, PNG, WARC,
        # info.json, description, thumbnail, subs, manifest_pdf, etc. Skip
        # ``media`` / ``media_2`` roles since the primary media file is
        # emitted at the top of the loop above.
        downloads_root = config.DOWNLOADS_DIR.resolve()
        for role, rel in meta.get("artifacts", {}).items():
            if role.startswith("media"):
                continue
            # Defense in depth: meta_json is generated by Capsule, but the
            # export reads the unsigned DB copy. Reject any path that isn't
            # a clean relative path under DOWNLOADS_DIR so a tampered row
            # can't exfiltrate arbitrary files into the bundle.
            rel_path = Path(rel)
            if rel_path.is_absolute() or ".." in rel_path.parts:
                continue
            abs_path = (config.DOWNLOADS_DIR / rel_path).resolve()
            try:
                abs_path.relative_to(downloads_root)
            except ValueError:
                continue
            if not abs_path.is_file():
                continue
            yield (
                abs_path,
                f"downloads/{stem}/{abs_path.name}",
                role,
            )

        # The meta.json + sig + checksums + manifest.pdf are not listed in
        # meta["artifacts"] (the manifest PDF is — see Track A commit 3 —
        # but meta.json + sig + checksums.txt are not). Emit explicitly.
        for tail in (".meta.json", ".meta.json.sig", ".checksums.txt"):
            p = item_abs / f"{stem}{tail}"
            if p.is_file():
                yield (
                    p,
                    f"downloads/{stem}/{p.name}",
                    f"meta{tail}",
                )


def build_bundle(
    conn: sqlite3.Connection,
    *,
    case_id: int,
    out_dir: Path | None = None,
    lang: str | None = None,
) -> ExportResult:
    """Build a signed zip + PDF + verifier for ``case_id``.

    ``out_dir`` defaults to ``$CAPSULE_CONFIG_DIR/exports/`` so exports
    persist across restarts and never share a folder with downloads.

    ``lang`` selects the locale for the rendered ``case_report.pdf``.
    Defaults to ``config.DEFAULT_LANG`` so existing call sites keep
    working without churn; the export endpoint plumbs the active UI
    locale through.
    """
    out_dir = out_dir or (config.CONFIG_DIR / "exports")
    out_dir.mkdir(parents=True, exist_ok=True)
    lang = lang or config.DEFAULT_LANG

    plan = plan_for_case(conn, case_id)
    case = plan.case

    # Collect file records — compute hashes once, on the source files.
    file_records: list[dict[str, Any]] = []
    artifact_paths: list[tuple[Path, str, str]] = list(_iter_artifact_paths(plan))
    for abs_path, rel_in_zip, role in artifact_paths:
        h = postprocess.compute_hashes(abs_path)
        file_records.append(
            {
                "path": rel_in_zip,
                "role": role,
                "size_bytes": h["size_bytes"],
                "md5": h["md5"],
                "sha256": h["sha256"],
            }
        )

    # Audit log JSON (per-case slice).
    audit_entries = list(audit.iter_entries(conn, case_id=case_id))
    for e in audit_entries:
        # The verifier re-derives row_hash from the same canonical encoding
        # used in audit.canonical_encode (sort_keys, compact separators,
        # ensure_ascii=True). Keep ``details_json`` byte-for-byte identical
        # so the recipient's verifier sees the same input we hashed.
        e["details_json"] = json.dumps(
            e.pop("details"), sort_keys=True, separators=(",", ":"),
            ensure_ascii=True,
        )
    audit_bytes = json.dumps(
        audit_entries, indent=2, ensure_ascii=True, default=str
    ).encode("utf-8")

    # PDF report. Locale flips labels, page direction, and the font
    # stack so RTL Arabic / CJK glyphs render without tofu.
    pdf_bytes = pdf_report.render_case_report(
        case=case, items=plan.items, lang=lang,
    )

    # Verifier script.
    verifier_bytes = verifier_template_path().read_bytes()

    # Public key.
    kp = signing.ensure_keypair()
    fingerprint = signing.fingerprint(kp.public)
    pubkey_bytes = signing.public_key_path().read_bytes()

    timestamp = _utcnow_compact()
    zip_name = f"{case.slug}_{timestamp}.zip"
    zip_path = out_dir / zip_name

    # Build the manifest before we know its own size (it's not self-listed —
    # the signature covers manifest.json so the manifest doesn't need to
    # list itself).
    manifest = {
        "schema_version": 1,
        "case": {
            "id": case.id,
            "slug": case.slug,
            "name": case.name,
            "status": case.status,
        },
        "exported_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "exporter_app_version": __version__,
        "signing_key_fingerprint": fingerprint,
        "files": file_records,
    }
    manifest_bytes = json.dumps(
        manifest, indent=2, sort_keys=True, ensure_ascii=False
    ).encode("utf-8")
    manifest_sig = signing.sign(manifest_bytes)

    readme = (
        f"Capsule evidence export\n"
        f"=======================\n\n"
        f"Case: {case.name} ({case.slug})\n"
        f"Items: {len(plan.items)}\n"
        f"Exported (UTC): {manifest['exported_at']}\n"
        f"App version: {__version__}\n"
        f"Signing key fingerprint: {fingerprint}\n\n"
        "To verify integrity, run:\n"
        "    python verify.py .\n\n"
        "Verification re-checks every artifact's hash, every per-item\n"
        "signature, and the audit-log hash chain. The only dependency is\n"
        "the `cryptography` library (PyPI).\n\n"
        "The verifier (verify.py) is MIT-licensed; see LICENSE in this\n"
        "bundle for the exact terms.\n"
    ).encode("utf-8")

    # The recipient will run ``verify.py``; ship the MIT license alongside
    # so they know the terms under which they can run / redistribute it.
    license_path = config.PROJECT_ROOT / "LICENSE"
    license_bytes = (
        license_path.read_bytes() if license_path.is_file() else b""
    )

    # Write the zip.
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", manifest_bytes)
        zf.writestr("manifest.sig", manifest_sig)
        zf.writestr("public_key.pem", pubkey_bytes)
        zf.writestr("audit_log.json", audit_bytes)
        zf.writestr("verify.py", verifier_bytes)
        zf.writestr(EXPORT_README_NAME, readme)
        zf.writestr("case_report.pdf", pdf_bytes)
        if license_bytes:
            zf.writestr("LICENSE", license_bytes)
        for abs_path, rel_in_zip, _role in artifact_paths:
            zf.write(abs_path, rel_in_zip)

    manifest_path = out_dir / f"{case.slug}_{timestamp}.manifest.json"
    manifest_path.write_bytes(manifest_bytes)

    audit_id = audit.append(
        conn,
        "case.exported",
        case_id=case.id,
        actor="user",
        details={
            "zip": str(zip_path.name),
            "files": len(file_records),
            "fingerprint": fingerprint,
        },
    )

    return ExportResult(
        zip_path=zip_path,
        manifest_path=manifest_path,
        audit_log_entry_id=audit_id,
    )
